name: "Auto Tagging and Release"
description: "Creates auto tag and release"

inputs:
  main_branch_name:
    description: "Main branch name"
    required: true
  develop_branch_name:
    description: "Develop branch name"
    required: true
  GITHUBPAT:
    description: "GITHUB PAT"
    required: true

runs:
  using: "composite"
  steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Form tag name
        id: tagging
        shell: bash
        run: |
          git config user.name github-actions@github.com
          git config user.email github-actions
          git config --global http.postBuffer 1048576000
          git fetch --tags
          
          main_branch=${{ inputs.main_branch_name }}
          develop_branch_name=${{ inputs.develop_branch_name }}
          
          tags=$(git tag -l)
          
          if [ -z "$tags" ]; then
            latest_tag="v0.0.0"
          else
            repo_name=$(git config --get remote.origin.url | sed 's/.*\/\([^ ]*\/[^.]*\).*/\1/')
            latest_tag=$(curl -sL https://api.github.com/repos/$repo_name/releases | jq -r ".[0].tag_name")
          fi
          
          echo "previous latest tag : $latest_tag"
          version=`echo $latest_tag| cut -d. -f1`
          major=`echo $latest_tag | cut -d. -f2`
          minor=`echo $latest_tag | cut -d. -f3`
          branch=${{ steps.extract_branch.outputs.branch }}
          prerelease=false
          
          if [[ $branch == $main_branch_name &&  "${{ github.event.inputs.create_new_tag }}" == "true" ]] ; then
            version=${version#"v"}
            version=`expr $version + 1`
            major=0
            minor=0
            version=v${version}
            echo $version
          elif [ $branch == $main_branch_name ]; then
            prerelease=true
            minor=0
            major=`expr $major + 1`
            
          elif [ $branch == $develop_branch_name ]; then
              prerelease=true
              echo $branch
              if [ -z "$minor" ]; then
                 minor=1
              else
                  minor=`expr $minor + 1`
              fi
          fi
          tag_name=$version.$major.$minor
          echo "new tag is : $tag_name"
          echo ::set-output name=prerelease::$prerelease
          echo ::set-output name=tag_id::$tag_name
          
      - name: create tag
        id: creatre tag
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPAT }}
        run: |
       
                if [[ "${{ steps.tagging.outputs.prerelease }}" == "true" ]] ; then

                    gh release create  ${{ steps.tagging.outputs.tag_id }} --prerelease 

                else
                    git tag -a ${{ steps.tagging.outputs.tag_id }} -m  " new tag ${{ steps.tagging.outputs.tag_id }} created"
                    git push --tags origin master
                fi
          

branding:
  icon: "book-open"
  color: "white"
